1D Numpy Array



In [ ]:
a=['AC','BW','AC','AC','BW']
b=[10,87,34,65,21]

import numpy as np
np_a=np.array(a)
np_b=np.array(b)

print(type(a))
print(type(np_a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(np_a)
print(np_b)

['AC' 'BW' 'AC' 'AC' 'BW']
[10 87 34 65 21]


Array Operations

In [ ]:
np_b2=np_b*2
print(np_b2)

np_b3=np_b+np_b2
print(np_b3)
print(type(np_b3))

np_B=(np_b3**2)/(np_b**3)
print(np_B)
print(type(np_B))

[ 20 174  68 130  42]
[ 30 261 102 195  63]
<class 'numpy.ndarray'>
[0.9        0.10344828 0.26470588 0.13846154 0.42857143]
<class 'numpy.ndarray'>


Array Slicing, Subsetting

In [ ]:
np_B_less=np_B[np_B<0.2]  #subsetting with conditions
print(np_B_less)
print(type(np_B_less))

print(np_B[2:4])  #slicing

print(np_B[1]) #subsetting

[0.10344828 0.13846154]
<class 'numpy.ndarray'>
[0.26470588 0.13846154]
0.10344827586206896


In [ ]:
AC_value=np_b[np_a=='AC']  #subsetting with conditions
print(AC_value)

BW_value=np_b[np_a!='AC']
print(BW_value)

[10 34 65]
[87 21]


2D Numpy Array.
Array of list of list is called 2D Numpy Array.

In [ ]:
H_W_A=[[181, 88.4, 35],[184, 91.7, 31],[183, 90.5, 29],[188, 85.2, 30],[189, 87.3, 33]]
#H=height, W=weight, A=age
np_H_W_A=np.array(H_W_A)
print(np_H_W_A)
print(np_H_W_A.shape)

[[181.   88.4  35. ]
 [184.   91.7  31. ]
 [183.   90.5  29. ]
 [188.   85.2  30. ]
 [189.   87.3  33. ]]
(5, 3)


Subsetting & Slicing

Print out the 4th row of np_H_W_A



In [ ]:
print(np_H_W_A[3,:])

[188.   85.2  30. ]


Print the entire second column of np_H_W_A : **Weight**

In [ ]:
print(np_H_W_A[:,1])

[88.4 91.7 90.5 85.2 87.3]


Print out height of 2th person

In [ ]:
print(np_H_W_A[1,0])

184.0


Print out weight & age of 4th & 5th person

In [ ]:
print(np_H_W_A[3:,1:])

[[85.2 30. ]
 [87.3 33. ]]


Mean, Median, Standerd deviation

Print mean height

In [ ]:
print(np.mean(np_H_W_A[:,0]))

185.0


Print median of age

In [ ]:
print(np.median(np_H_W_A[:,2]))

31.0


Print Standerd deviation of weight

In [ ]:
print(np.std(np_H_W_A[:,1]))

2.3025203582161877


Print mean of 2nd to 4th person's weight

In [ ]:
print(np.mean(np_H_W_A[1:4,1]))

89.13333333333333
